### ISSUE TITLE
Problème Player Audio tvOs 14

### ISSUE THREAD

**Issue by Juliensindatry** [Radiomyme/Radio-Play-for-iOS-and-tvOS-compatible-iOS-12-tvOS-12#3]
Hello, Le problème est du à la mise à jour ios14. 
Le player affiche uniquement la progression d'un titre sur un fond noir (plus de cover etc ... )

**Comment by Radiomyme** [comment]
Bonjour, nous sommes sur le coup (avec énormément de retard). Le bug est corrigé normalement. Merci pour le signalement :)
